// Generacion de PDFs OEX
import jsPDF from "jspdf";
import { numero } from "../utils/numero";
import logoOEX from "../assets/LOGOOEX.png";
import { notaShein, resumenShein, totalProductoShein } from "../utils/calculosShein";
import { tarifaPorTipoEnvio, calcularTotalesTrackings, costoItemCotPaq, totalItemCotPaq, librasCotPaq, totalCotPaq, totalEnvioCotPaq } from "../utils/calculosPaqueteria";

const NARANJA=[244,86,45],NAVY=[15,36,69],GRAFITO=[34,37,43],GRIS_MEDIO=[138,143,152],GRIS_CLARO=[216,218,221],PAPEL=[247,246,243],BLANCO=[255,255,255];
const formatoFecha=iso=>new Date(iso||Date.now()).toLocaleDateString("es-NI",{year:"numeric",month:"long",day:"numeric"});
const pdfHeader=(doc,{titulo,numeroDoc,fechaISO})=>{doc.setFillColor(...NAVY);doc.rect(0,0,210,32,"F");doc.setFillColor(...NARANJA);doc.rect(0,0,210,2.5,"F");doc.addImage(logoOEX,"PNG",7,4,27,24);doc.setTextColor(...BLANCO);doc.setFontSize(12);doc.setFont("helvetica","bold");doc.text(titulo,196,13,{align:"right"});doc.setFontSize(9);doc.setFont("helvetica","normal");if(numeroDoc)doc.text(`No. ${numeroDoc}`,196,20,{align:"right"});doc.text(`Fecha de emisión: ${formatoFecha(fechaISO)}`,196,26,{align:"right"});doc.setTextColor(...GRAFITO);};
const pdfLineaTipoCambio=(doc,y,totalUSD,empresa)=>{const tc=numero(empresa?.tipoCambio);if(!tc)return y;doc.setFontSize(9);doc.setFont("helvetica","normal");doc.setTextColor(...GRAFITO);doc.text(`Tipo de cambio: C$${tc.toFixed(2)} por US$1.00`,14,y);doc.text(`Total en córdobas: C$${(totalUSD*tc).toFixed(2)}`,14,y+5);return y+12;};
const pdfFooter=(doc,nota,empresa)=>{const y=265;doc.setDrawColor(...GRIS_CLARO);doc.line(14,y,196,y);doc.setFontSize(8);doc.setTextColor(...GRIS_MEDIO);doc.text(nota||"",14,y+6,{maxWidth:182});const contacto=[empresa?.telefono?`Tel/WhatsApp: ${empresa.telefono}`:null,empresa?.correo?`Correo: ${empresa.correo}`:null,empresa?.web||null,empresa?.instagram?`IG: ${empresa.instagram}`:null].filter(Boolean).join("   ·   ");doc.setFont("helvetica","bold");doc.setTextColor(...NAVY);doc.text(`${empresa?.nombre||"OEX"} — Estados Unidos · Nicaragua`,14,285);doc.setFont("helvetica","normal");doc.setTextColor(...GRIS_MEDIO);if(contacto)doc.text(contacto,14,290);doc.text("Documento generado por OEX Nicaragua.",14,295);};
const pdfSaltoPagina=(doc,y,minimo=45)=>{if(y>297-minimo){doc.addPage();return 20;}return y;};

export const generarPDFShein=(pedido,ctx,empresa)=>{const doc=new jsPDF();pdfHeader(doc,{titulo:"RECIBO DE PEDIDO SHEIN",numeroDoc:pedido.numero,fechaISO:pedido.fechaISO});let y=42;doc.setFontSize(11);doc.setFont("helvetica","bold");doc.text(`Cliente: ${pedido.cliente}`,14,y);doc.setFont("helvetica","normal");doc.text(`Contacto: ${pedido.contacto}`,14,y+6);doc.text(`Código de cliente: ${pedido.clienteCodigo||"—"}`,14,y+12);doc.setFont("helvetica","bold");doc.text(`Estado: ${pedido.estado}`,130,y);y+=22;doc.setFillColor(...PAPEL);doc.rect(14,y-5,182,8,"F");doc.setFontSize(9);doc.text("Descripción",17,y);doc.text("Uds.",130,y);doc.text("Costo",155,y);doc.text("Total",190,y,{align:"right"});doc.setFont("helvetica","normal");y+=8;(pedido.productos||[]).forEach(p=>{y=pdfSaltoPagina(doc,y);doc.text(String(p.descripcion||"").slice(0,48),17,y);doc.text(String(p.unidades||1),130,y);doc.text(`$${numero(p.costo_prenda).toFixed(2)}`,155,y);doc.text(`$${numero(p.total_producto).toFixed(2)}`,190,y,{align:"right"});y+=6;});y+=4;doc.line(14,y,196,y);y+=8;doc.text(`Abono: $${numero(pedido.abono).toFixed(2)}`,130,y);doc.text(`Saldo: $${numero(pedido.saldo).toFixed(2)}`,130,y+6);doc.setFont("helvetica","bold");doc.setFontSize(13);doc.setTextColor(...NARANJA);doc.text(`Total: $${numero(pedido.total).toFixed(2)}`,190,y,{align:"right"});doc.setTextColor(...GRAFITO);y=pdfLineaTipoCambio(doc,y+14,numero(pedido.total),empresa);pdfFooter(doc,pedido.nota||notaShein({modo:ctx?.modo||"con_financiamiento",tipoDocumento:"pedido"}),empresa);doc.save(`${pedido.numero||"pedido"}.pdf`);};

export const generarPDFCotizacionShein=({cliente,contacto,productos,ctx,empresa})=>{const doc=new jsPDF();pdfHeader(doc,{titulo:"COTIZACIÓN SHEIN",fechaISO:new Date().toISOString()});let y=42;doc.setFont("helvetica","bold");doc.text(`Cliente: ${cliente||"—"}`,14,y);doc.setFont("helvetica","normal");doc.text(`Contacto: ${contacto||"—"}`,14,y+6);y+=20;const r=resumenShein(productos,ctx);doc.setFont("helvetica","bold");doc.text("Descripción",14,y);doc.text("Costo",145,y);doc.text("Total",190,y,{align:"right"});doc.setFont("helvetica","normal");y+=6;productos.forEach(p=>{y=pdfSaltoPagina(doc,y);doc.text(String(p.descripcion||"").slice(0,50),14,y);doc.text(`$${numero(p.costo_prenda).toFixed(2)}`,145,y);doc.text(`$${totalProductoShein(p,ctx).toFixed(2)}`,190,y,{align:"right"});y+=6;});y+=8;doc.setFont("helvetica","bold");doc.setTextColor(...NARANJA);doc.text(`Total estimado: $${r.total.toFixed(2)}`,190,y,{align:"right"});doc.setTextColor(...GRAFITO);y=pdfLineaTipoCambio(doc,y+12,r.total,empresa);pdfFooter(doc,notaShein({modo:ctx.modo,tipoDocumento:"cotizacion"}),empresa);doc.save("cotizacion-shein.pdf");};

export const generarPDFCotizacionPaq=({cliente,contacto,items,form,tarifas,empresa})=>{const doc=new jsPDF();pdfHeader(doc,{titulo:"COTIZACIÓN PAQUETERÍA",fechaISO:new Date().toISOString()});let y=42;doc.setFont("helvetica","bold");doc.text(`Cliente: ${cliente||"—"}`,14,y);doc.setFont("helvetica","normal");doc.text(`Destino: ${form.destino} · ${form.tipoEnvio}`,14,y+6);y+=20;doc.setFont("helvetica","bold");doc.text("Producto",14,y);doc.text("Peso",110,y);doc.text("Costo",140,y);doc.text("Total",190,y,{align:"right"});doc.setFont("helvetica","normal");y+=6;items.forEach(i=>{y=pdfSaltoPagina(doc,y);doc.text(String(i.descripcion||"").slice(0,40),14,y);doc.text(`${numero(i.peso).toFixed(1)} lb`,110,y);doc.text(`$${costoItemCotPaq(i).toFixed(2)}`,140,y);doc.text(`$${totalItemCotPaq(i).toFixed(2)}`,190,y,{align:"right"});y+=6;});y+=4;doc.line(14,y,196,y);y+=8;doc.text(`Peso total: ${librasCotPaq(items).toFixed(1)} lb`,14,y);doc.text(`Envío estimado: $${totalEnvioCotPaq(tarifas,form,items).toFixed(2)}`,14,y+6);doc.setFont("helvetica","bold");doc.setTextColor(...NARANJA);const totalEstimado=totalCotPaq(tarifas,form,items);doc.text(`Total estimado: $${totalEstimado.toFixed(2)}`,190,y,{align:"right"});doc.setTextColor(...GRAFITO);pdfFooter(doc,"Cotización válida por 24 horas. El precio final puede variar según peso real al llegar el paquete.",empresa);doc.save("cotizacion-paqueteria.pdf");};

export const generarDetalleEnvio=(envio,tarifas,empresa)=>{const doc=new jsPDF();pdfHeader(doc,{titulo:"RECIBO DE ENVÍO",numeroDoc:envio.numero,fechaISO:envio.fechaISO});let y=42;doc.setFontSize(11);doc.setFont("helvetica","bold");doc.text(`Cliente: ${envio.cliente}`,14,y);doc.setFont("helvetica","normal");doc.text(`Código de cliente: ${envio.clienteCodigo||"—"}`,14,y+6);doc.setFont("helvetica","bold");doc.text(`Destino: ${envio.destino}`,130,y);doc.setFont("helvetica","normal");doc.text(`Estado: ${envio.estado}`,130,y+6);y+=22;const td=envio.trackings||[];doc.setFillColor(...PAPEL);doc.rect(14,y-5,182,8,"F");doc.setFont("helvetica","bold");doc.setFontSize(9);doc.text("Tracking",17,y);doc.text("Tipo",95,y);doc.text("Peso",120,y);doc.text("Tarifa/lb",148,y);doc.text("Total",190,y,{align:"right"});doc.setFont("helvetica","normal");y+=8;td.forEach(t=>{y=pdfSaltoPagina(doc,y);const tipo=t.tipoEnvio||envio.tipoEnvio,tarifaLb=tarifaPorTipoEnvio(tarifas,envio,tipo);doc.text(String(t.codigo||"—"),17,y);doc.text(tipo,95,y);doc.text(`${numero(t.peso).toFixed(1)} lb`,120,y);doc.text(`$${tarifaLb.toFixed(2)}`,148,y);doc.text(`$${(numero(t.peso)*tarifaLb).toFixed(2)}`,190,y,{align:"right"});y+=6;});const {total}=calcularTotalesTrackings(tarifas,envio,td);y+=4;doc.line(14,y,196,y);y+=8;if(numero(envio.descuento)>0){doc.text(`Descuento aplicado: -$${numero(envio.descuento).toFixed(2)}`,14,y);y+=6;}doc.setFont("helvetica","bold");doc.setFontSize(13);doc.setTextColor(...NARANJA);doc.text(`Total: $${total.toFixed(2)}`,190,y,{align:"right"});doc.setTextColor(...GRAFITO);y=pdfLineaTipoCambio(doc,y+14,total,empresa);pdfFooter(doc,"Envío procesado por OEX. Gracias por confiar en nosotros.",empresa);doc.save(`${envio.numero||"envio"}.pdf`);};

// Reporte operativo de paquetes que ya están listos para retirar al proveedor en Bodega OEX.
// Se agrupa por proveedor y dentro de cada proveedor por tipo/destino.
export const generarPDFBodegaProveedor=({trackings=[],proveedores=[],empresa})=>{
 const doc=new jsPDF();pdfHeader(doc,{titulo:"RETIRO BODEGA OEX",fechaISO:new Date().toISOString()});
 const proveedorNombre=id=>proveedores.find(p=>String(p.id)===String(id))?.nombre||"Proveedor sin asignar";
 const grupos=new Map();trackings.forEach(t=>{const k=String(t.proveedorAduanaId||"sin");if(!grupos.has(k))grupos.set(k,[]);grupos.get(k).push(t);});
 const totalLb=trackings.reduce((a,t)=>a+numero(t.peso),0);let y=43;
 doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text("Resumen de retiro",14,y);y+=7;doc.setFontSize(9);doc.setFont("helvetica","normal");doc.text(`Total paquetes: ${trackings.length}`,14,y);doc.text(`Total libras: ${totalLb.toFixed(2)} lb`,75,y);doc.text(`Proveedores: ${grupos.size}`,145,y);y+=10;
 [...grupos.entries()].forEach(([id,items],gi)=>{y=pdfSaltoPagina(doc,y,65);const lbs=items.reduce((a,t)=>a+numero(t.peso),0);doc.setFillColor(...NAVY);doc.roundedRect(14,y-5,182,12,2,2,"F");doc.setTextColor(...BLANCO);doc.setFont("helvetica","bold");doc.setFontSize(10);doc.text(proveedorNombre(id),18,y+2);doc.text(`${items.length} paquetes · ${lbs.toFixed(2)} lb`,192,y+2,{align:"right"});doc.setTextColor(...GRAFITO);y+=15;
  const sub=new Map();items.forEach(t=>{const k=`${t.tipoEnvio||"—"}|${t.destino||"—"}`;if(!sub.has(k))sub.set(k,[]);sub.get(k).push(t);});
  [...sub.entries()].forEach(([clave,filas])=>{y=pdfSaltoPagina(doc,y,48);const [tipo,destino]=clave.split("|");const subLb=filas.reduce((a,t)=>a+numero(t.peso),0);doc.setFont("helvetica","bold");doc.setFontSize(9);doc.setTextColor(...NAVY);doc.text(`${tipo} · ${destino}`,16,y);doc.setFont("helvetica","normal");doc.setTextColor(...GRIS_MEDIO);doc.text(`${filas.length} paquetes · ${subLb.toFixed(2)} lb`,192,y,{align:"right"});y+=6;doc.setFillColor(...PAPEL);doc.rect(14,y-4,182,7,"F");doc.setTextColor(...GRAFITO);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text("ID almacén",17,y);doc.text("Tracking",57,y);doc.text("Cliente",126,y);doc.text("Peso",190,y,{align:"right"});doc.setFont("helvetica","normal");y+=7;
   filas.forEach(t=>{y=pdfSaltoPagina(doc,y,28);doc.setFontSize(8.5);doc.text(String(t.almacenId||"—").slice(0,18),17,y);doc.text(String(t.tracking||t.codigo||"—").slice(0,28),57,y);doc.text(String(t.cliente||"—").slice(0,25),126,y);doc.text(`${numero(t.peso).toFixed(2)} lb`,190,y,{align:"right"});y+=6;});y+=5;
  });if(gi<[...grupos.keys()].length-1)y+=2;
 });
 pdfFooter(doc,"Detalle interno para coordinación de retiro en Bodega OEX. Agrupado por proveedor, tipo de envío y destino.",empresa);doc.save(`retiro-bodega-oex-${new Date().toISOString().slice(0,10)}.pdf`);
};

export const generarPDFReporteFinanciero=({ventasPorMes=[],gastosPorCategoria=[],topClientes=[],kpis={},empresa})=>{const doc=new jsPDF();pdfHeader(doc,{titulo:"REPORTE FINANCIERO",fechaISO:new Date().toISOString()});let y=42;doc.setFont("helvetica","bold");doc.setFontSize(12);doc.text("Resumen general",14,y);y+=8;[["Ventas SHEIN",numero(kpis.ventasShein)],["Ventas Paquetería",numero(kpis.ventasPaq)],["Ganancia real Paquetería",numero(kpis.gananciaPaq)],["Gastos operativos",numero(kpis.totalGastos)],["Utilidad neta operativa",numero(kpis.utilidadNeta)]].forEach(([l,v])=>{doc.setFont("helvetica",l==="Utilidad neta operativa"?"bold":"normal");doc.text(l,17,y);doc.text(`$${v.toFixed(2)}`,190,y,{align:"right"});y+=7;});y+=6;doc.setFont("helvetica","bold");doc.text("Ventas y gastos por mes",14,y);y+=8;doc.setFont("helvetica","normal");ventasPorMes.forEach(m=>{y=pdfSaltoPagina(doc,y);doc.text(`${m.mes}: SHEIN $${numero(m.shein).toFixed(2)} · Paquetería $${numero(m.paqueteria).toFixed(2)} · Gastos $${numero(m.gastos).toFixed(2)} · Balance $${numero(m.balance).toFixed(2)}`,17,y);y+=6;});y+=6;doc.setFont("helvetica","bold");doc.text("Gastos por categoría",14,y);y+=7;doc.setFont("helvetica","normal");gastosPorCategoria.forEach(g=>{y=pdfSaltoPagina(doc,y);doc.text(`${g.categoria} · ${numero(g.pct).toFixed(0)}%`,17,y);doc.text(`$${numero(g.monto).toFixed(2)}`,190,y,{align:"right"});y+=6;});y+=6;doc.setFont("helvetica","bold");doc.text("Top clientes",14,y);y+=7;doc.setFont("helvetica","normal");topClientes.forEach(c=>{y=pdfSaltoPagina(doc,y);doc.text(String(c.nombre||c.cliente||"Cliente"),17,y);doc.text(`$${numero(c.total||c.monto).toFixed(2)}`,190,y,{align:"right"});y+=6;});pdfFooter(doc,"Reporte interno de gestión financiera OEX.",empresa);doc.save("reporte-financiero-oex.pdf");};
