import { useEffect, useMemo, useState } from "react";
import { RefreshCw, PackageSearch, CheckCircle2, AlertTriangle, History } from "lucide-react";
import { asignarRecepcionGlobal, importarLecturaGlobalConnection, listarRecepcionesGlobal, listarRunsGlobal, sincronizarGlobalConnection } from "../../services/globalConnectionService";
import "../../styles/GlobalConnection.css";

export default function GlobalConnection({clientes=[],auth,mostrarToast,cargarDatos}){
 const [recepciones,setRecepciones]=useState([]),[runs,setRuns]=useState([]),[cargando,setCargando]=useState(true),[sync,setSync]=useState(false),[asignando,setAsignando]=useState(null);
 const [form,setForm]=useState({});
 const [progreso,setProgreso]=useState(null);
 const [lectura,setLectura]=useState("");
 const [copiado,setCopiado]=useState(false);
 const lectorGlobal=`javascript:(async()=>{try{const links=[...document.querySelectorAll('a[href*="whs_detail.asp?id="]')],ids=[...new Set(links.map(a=>{try{return new URL(a.href,location.href).searchParams.get('id')}catch{return null}}).filter(Boolean))];if(!ids.length)throw new Error('No encontré números de almacén. Abre Almacén.');const out=[];for(const id of ids){const r=await fetch('/appl2.0/agent/whs_detail.asp?id='+encodeURIComponent(id),{credentials:'include'});if(!r.ok)throw new Error('No pude abrir almacén '+id);const h=await r.text(),doc=new DOMParser().parseFromString(h,'text/html'),inputs=[...doc.querySelectorAll('input')];const valByLabel=(label)=>{for(const el of doc.querySelectorAll('td,th,label,span,div')){if((el.textContent||'').trim().toLowerCase()===label.toLowerCase()){const row=el.closest('tr')||el.parentElement;if(row){const inp=row.querySelector('input');if(inp&&inp.value)return inp.value.trim();const cells=[...row.querySelectorAll('td')];const i=cells.indexOf(el.closest('td'));if(i>=0){for(let j=i+1;j<cells.length;j++){const x=cells[j].querySelector('input');if(x&&x.value)return x.value.trim()}}}}}return''};let tracking=valByLabel('Tracking');if(!tracking){const inp=inputs.find(x=>/tracking/i.test((x.name||'')+' '+(x.id||'')));tracking=inp?.value?.trim()||''}const fecha=valByLabel('Fecha')||null;const referencia=valByLabel('Referencia')||null;if(tracking&&!/^factura$/i.test(tracking)&&tracking!=='N/A')out.push({almacen_id:id,tracking,fecha_miami:fecha,nombre_global:referencia})}if(!out.length)throw new Error('Abrí los almacenes, pero no encontré el campo Tracking.');const data=JSON.stringify(out);try{await navigator.clipboard.writeText(data)}catch{prompt('Copia esta lectura de OEX:',data);return}alert('OEX: '+out.length+' paquetes copiados. Regresa a OEX y pégalos.')}catch(e){alert('OEX: '+e.message)}})();`;
 const copiarLector=async()=>{try{await navigator.clipboard.writeText(lectorGlobal);setCopiado(true);mostrarToast?.("Lector copiado. Ahora créalo como marcador en Chrome.","success");setTimeout(()=>setCopiado(false),2500)}catch{mostrarToast?.("Chrome no permitió copiar el lector.","error")}};
 const importarLectura=async()=>{try{const items=JSON.parse(lectura);const r=await importarLecturaGlobalConnection(items,auth);mostrarToast?.(`Lectura importada: ${r.coincidencias} coincidencias · ${r.nuevos} nuevos`,"success");setLectura("");await Promise.all([cargar(),cargarDatos?.()])}catch(e){mostrarToast?.(e.message||"Lectura inválida.","error")}};
 const cargar=async()=>{setCargando(true);try{const [r,h]=await Promise.all([listarRecepcionesGlobal(),listarRunsGlobal()]);setRecepciones(r);setRuns(h)}catch(e){mostrarToast?.(e.message,"error")}finally{setCargando(false)}};
 useEffect(()=>{cargar()},[]);
 const pendientes=useMemo(()=>recepciones.filter(x=>x.estado==="sin_asignar"),[recepciones]);
 const sincronizar=async()=>{setSync(true);setProgreso({procesados:0,total:0,lote:0});try{const r=await sincronizarGlobalConnection({onProgress:setProgreso});mostrarToast?.(`Global Connect: ${r.prealertasConfirmadas} prealertas confirmadas · ${r.sinAsignarNuevos} nuevos sin asignar`,"success");await Promise.all([cargar(),cargarDatos?.()])}catch(e){mostrarToast?.(e.message,"error")}finally{setSync(false);setProgreso(null)}};
 const asignar=async(r)=>{const f=form[r.id]||{};const cliente=clientes.find(c=>String(c.id)===String(f.clienteId));setAsignando(r.id);try{await asignarRecepcionGlobal({recepcion:r,cliente,destino:f.destino,tipoEnvio:f.tipoEnvio,auth});mostrarToast?.("Paquete asignado y enviado a Envíos activos.","success");await Promise.all([cargar(),cargarDatos?.()])}catch(e){mostrarToast?.(e.message,"error")}finally{setAsignando(null)}};
 const last=runs[0];
 return <div className="gc-page">
  <section className="gc-hero"><div><span className="gc-eyebrow">Recepción Miami</span><h2>Global Connection</h2><p>Confirma prealertas recibidas y organiza paquetes que todavía no tienen cliente asignado.</p></div></section>
  {last&&<section className="gc-summary"><div><CheckCircle2 size={18}/><span>Última sincronización</span></div><strong>{last.total_detectados} detectados</strong><span>{last.prealertas_confirmadas} prealertas confirmadas</span><span>{last.sin_asignar_nuevos} nuevos sin asignar</span><span>{last.actualizados_sin_regresion} sin retroceder estado</span>{last.errores>0&&<span className="gc-warning">{last.errores} errores</span>}</section>}
  <div className="gc-kpis"><div><PackageSearch/><span>Por asignar</span><strong>{pendientes.length}</strong></div><div><CheckCircle2/><span>Coincidencias</span><strong>{recepciones.filter(x=>x.estado==="coincidencia").length}</strong></div><div><History/><span>Asignados manualmente</span><strong>{recepciones.filter(x=>x.estado==="asignado").length}</strong></div></div>
  <section className="gc-panel"><div className="gc-panel-head"><div><h3>Sincronizar desde tu navegador</h3><p>1. Pulsa “Copiar lector”. 2. En Chrome crea un marcador llamado OEX Sync y pega el lector como URL. 3. Abre Global Connection → Almacén y pulsa OEX Sync. 4. Regresa aquí y pega la lectura.</p></div></div>
   <div className="gc-assign"><button className="btn btn-secondary" type="button" onClick={copiarLector}>{copiado?"✓ Lector copiado":"Copiar lector OEX — página actual"}</button><textarea value={lectura} onChange={e=>setLectura(e.target.value)} placeholder="Pega aquí la lectura copiada por OEX Sync…" rows={3}/><button className="btn btn-primary" onClick={importarLectura} disabled={!lectura.trim()}>Importar lectura</button></div>
  </section>
  <section className="gc-panel"><div className="gc-panel-head"><div><h3>Paquetes sin asignar</h3><p>Recibidos en Miami que no estaban registrados en OEX.</p></div></div>
   {cargando?<p>Cargando recepciones…</p>:pendientes.length===0?<div className="gc-empty"><CheckCircle2 size={26}/><b>Todo está asignado</b><span>No hay paquetes pendientes de cliente.</span></div>:<div className="gc-list">{pendientes.map(r=>{const f=form[r.id]||{};return <article className="gc-card" key={r.id}><div className="gc-card-main"><div><small>TRACKING</small><b>{r.tracking}</b></div><div><small>ID ALMACÉN</small><b>{r.almacen_id}</b></div><div><small>NOMBRE / REFERENCIA</small><b>{r.nombre_global||"Sin nombre"}</b></div><div><small>RECIBIDO MIAMI</small><b>{r.fecha_miami?new Date(r.fecha_miami).toLocaleDateString():"—"}</b></div></div><div className="gc-assign"><select value={f.clienteId||""} onChange={e=>setForm(x=>({...x,[r.id]:{...f,clienteId:e.target.value}}))}><option value="">Asignar cliente…</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><select value={f.destino||""} onChange={e=>setForm(x=>({...x,[r.id]:{...f,destino:e.target.value}}))}><option value="">Destino…</option><option>Managua</option><option>Ometepe</option></select><select value={f.tipoEnvio||""} onChange={e=>setForm(x=>({...x,[r.id]:{...f,tipoEnvio:e.target.value}}))}><option value="">Tipo…</option><option>Aéreo</option><option>Marítimo</option></select><button className="btn btn-primary" disabled={asignando===r.id} onClick={()=>asignar(r)}>{asignando===r.id?"Asignando…":"Asignar y activar"}</button></div></article>})}</div>}
  </section>
  <section className="gc-panel"><div className="gc-panel-head"><div><h3>Historial de sincronización</h3><p>Resumen de lo que OEX hizo en Global Connect.</p></div></div><div className="gc-history">{runs.map(r=><details key={r.id}><summary><span>{new Date(r.creado_en).toLocaleString()}</span><b>{r.total_detectados} detectados · {r.prealertas_confirmadas} confirmados · {r.sin_asignar_nuevos} nuevos</b></summary><div className="gc-detail">{(r.detalle||[]).map((d,i)=><div key={i}><code>{d.tracking||d.almacenId||"—"}</code><span>{String(d.accion||"").replaceAll("_"," ")}</span></div>)}</div></details>)}</div>
  </section>
 </div>
}
