import { useEffect, useMemo, useState } from "react";
import { RefreshCw, PackageSearch, CheckCircle2, AlertTriangle, History } from "lucide-react";
import { asignarRecepcionGlobal, importarLecturaGlobalConnection, listarRecepcionesGlobal, listarRunsGlobal, sincronizarGlobalConnection } from "../../services/globalConnectionService";
import "../../styles/GlobalConnection.css";

export default function GlobalConnection({clientes=[],auth,mostrarToast,cargarDatos}){
 const [recepciones,setRecepciones]=useState([]),[runs,setRuns]=useState([]),[cargando,setCargando]=useState(true),[sync,setSync]=useState(false),[asignando,setAsignando]=useState(null);
 const [form,setForm]=useState({});
 const [progreso,setProgreso]=useState(null);
 const [lectura,setLectura]=useState("");
 const [importando,setImportando]=useState(false);
 const [copiado,setCopiado]=useState(false);
 const [ultimoResultado,setUltimoResultado]=useState(null);
 const [ultimaImportacion,setUltimaImportacion]=useState(()=>localStorage.getItem("oex_global_ultima_importacion")||"");
 const lectorGlobal=`javascript:(async()=>{try{const parse=async(url)=>{const r=await fetch(url,{credentials:'include'});if(!r.ok)throw new Error('No pude abrir '+url);return new DOMParser().parseFromString(await r.text(),'text/html')};const current=document;const pageLinks=[...current.querySelectorAll('a[href*="whs.asp"]')].map(a=>new URL(a.href,location.href).href);const pages=[...new Set([location.origin+'/appl2.0/agent/whs.asp',...pageLinks])].slice(0,5);const ids=[];for(const p of pages){const doc=p===location.href?current:await parse(p);for(const a of doc.querySelectorAll('a[href*="whs_detail.asp?id="]')){try{const id=new URL(a.href,location.href).searchParams.get('id');if(id&&!ids.includes(id))ids.push(id)}catch{}}}if(!ids.length)throw new Error('No encontré almacenes. Abre la pestaña Almacén.');const out=[];for(const id of ids){const doc=await parse('/appl2.0/agent/whs_detail.asp?id='+encodeURIComponent(id)),inputs=[...doc.querySelectorAll('input')];const valByLabel=(label)=>{for(const el of doc.querySelectorAll('td,th,label,span,div')){if((el.textContent||'').trim().toLowerCase()===label.toLowerCase()){const row=el.closest('tr')||el.parentElement;if(row){const inp=row.querySelector('input');if(inp&&inp.value)return inp.value.trim();const cells=[...row.querySelectorAll('td')],i=cells.indexOf(el.closest('td'));if(i>=0)for(let j=i+1;j<cells.length;j++){const x=cells[j].querySelector('input');if(x&&x.value)return x.value.trim()}}}}return''};let tracking=valByLabel('Tracking');if(!tracking){const inp=inputs.find(x=>/tracking/i.test((x.name||'')+' '+(x.id||'')));tracking=inp?.value?.trim()||''}const fecha=valByLabel('Fecha')||null,referencia=valByLabel('Reference')||valByLabel('Referencia')||null,instrucciones=valByLabel('Instructions')||valByLabel('Instrucciones')||null,status=valByLabel('Status')||null;if(tracking&&!/^factura$/i.test(tracking)&&tracking!=='N/A')out.push({almacen_id:id,tracking,fecha_miami:fecha,nombre_global:referencia,referencia_global:referencia,instrucciones_global:instrucciones,status_global:status})}if(!out.length)throw new Error('No encontré trackings en los almacenes.');const data=JSON.stringify(out);try{await navigator.clipboard.writeText(data)}catch{prompt('Copia esta lectura de OEX:',data);return}alert('OEX: '+out.length+' paquetes copiados de hasta 5 páginas. Regresa a OEX y pégalos.')}catch(e){alert('OEX: '+e.message)}})();`;
 const copiarLector=async()=>{try{await navigator.clipboard.writeText(lectorGlobal);localStorage.setItem("oex_global_lector_version","2026-09-27-ref-v2");setCopiado(true);mostrarToast?.("Lector copiado. Ahora créalo como marcador en Chrome.","success");setTimeout(()=>setCopiado(false),2500)}catch{mostrarToast?.("Chrome no permitió copiar el lector.","error")}};
 const importarLectura=async()=>{if(importando)return;setImportando(true);try{const raw=lectura.trim();if(/^javascript:/i.test(raw)||raw.includes("OEX Sync"))throw new Error("Pegaste el lector, no la lectura de paquetes. Ejecuta el marcador OEX Sync dentro de Global Connection y luego pega aquí el JSON que copia.");const items=JSON.parse(raw);const r=await importarLecturaGlobalConnection(items,auth);setUltimoResultado(r);const importadoEn=new Date().toISOString();setUltimaImportacion(importadoEn);localStorage.setItem("oex_global_ultima_importacion",importadoEn);const cambios=(r.detalle||[]).filter(d=>String(d.accion||"").includes("_a_"));mostrarToast?.(cambios.length?`Importación lista: ${cambios.length} cambiaron de estado. Revisa el detalle abajo.`:`Lectura importada: sin cambios de estado · ${r.nuevos} nuevos`,"success");setLectura("");await Promise.all([cargar(),cargarDatos?.()])}catch(e){mostrarToast?.(e.message||"Lectura inválida.","error")}finally{setImportando(false)}};
 const cargar=async()=>{setCargando(true);try{const [r,h]=await Promise.all([listarRecepcionesGlobal(),listarRunsGlobal()]);setRecepciones(r);setRuns(h)}catch(e){mostrarToast?.(e.message,"error")}finally{setCargando(false)}};
 useEffect(()=>{cargar()},[]);
 const pendientes=useMemo(()=>recepciones.filter(x=>x.estado==="sin_asignar"),[recepciones]);
 const sincronizar=async()=>{setSync(true);setProgreso({procesados:0,total:0,lote:0});try{const r=await sincronizarGlobalConnection({onProgress:setProgreso});mostrarToast?.(`Global Connect: ${r.prealertasConfirmadas} prealertas confirmadas · ${r.sinAsignarNuevos} nuevos sin asignar`,"success");await Promise.all([cargar(),cargarDatos?.()])}catch(e){mostrarToast?.(e.message,"error")}finally{setSync(false);setProgreso(null)}};
 const asignar=async(r)=>{const baseTipo=String(r?.detalle?.instrucciones_global||"").trim().toUpperCase()==="AIR"?"Aéreo":/(SEA|OCEAN|MARIT)/.test(String(r?.detalle?.instrucciones_global||"").trim().toUpperCase())?"Marítimo":"";const f=form[r.id]||{};const cliente=clientes.find(c=>String(c.id)===String(f.clienteId));setAsignando(r.id);try{await asignarRecepcionGlobal({recepcion:r,cliente,destino:f.destino,tipoEnvio:f.tipoEnvio||baseTipo,auth});mostrarToast?.("Paquete asignado y enviado a Envíos activos.","success");await Promise.all([cargar(),cargarDatos?.()])}catch(e){mostrarToast?.(e.message,"error")}finally{setAsignando(null)}};
 const last=runs[0];
 return <div className="gc-page">
  <section className="gc-hero"><div><span className="gc-eyebrow">Recepción Miami</span><h2>Global Connection</h2><p>Confirma prealertas recibidas y organiza paquetes que todavía no tienen cliente asignado.</p></div></section>
  {last&&<section className="gc-summary"><div><CheckCircle2 size={18}/><span>Última sincronización</span></div><strong>{last.total_detectados} detectados</strong><span>{last.prealertas_confirmadas} prealertas confirmadas</span><span>{last.sin_asignar_nuevos} nuevos sin asignar</span><span>{last.actualizados_sin_regresion} sin retroceder estado</span>{last.errores>0&&<span className="gc-warning">{last.errores} errores</span>}</section>}
  <div className="gc-kpis"><div><PackageSearch/><span>Por asignar</span><strong>{pendientes.length}</strong></div><div><CheckCircle2/><span>Coincidencias</span><strong>{recepciones.filter(x=>x.estado==="coincidencia").length}</strong></div><div><History/><span>Asignados manualmente</span><strong>{recepciones.filter(x=>x.estado==="asignado").length}</strong></div></div>
  <section className="gc-panel"><div className="gc-panel-head"><div><h3>Sincronizar desde tu navegador</h3>{ultimaImportacion&&<p><b>Última importación:</b> {new Date(ultimaImportacion).toLocaleString()}</p>}<p>1. Pulsa “Copiar lector”. 2. En Chrome crea un marcador llamado OEX Sync y pega el lector como URL. 3. Abre Global Connection → Almacén y pulsa OEX Sync. El lector revisará hasta las 5 páginas más recientes. 4. Regresa aquí y pega la lectura.</p></div></div>
   <div className="gc-assign"><button className="btn btn-secondary" type="button" onClick={copiarLector}>{copiado?"✓ Lector copiado":"Copiar lector OEX — últimas 5 páginas"}</button><textarea value={lectura} onChange={e=>setLectura(e.target.value)} placeholder="Pega aquí la lectura copiada por OEX Sync…" rows={3}/><button className="btn btn-primary" onClick={importarLectura} disabled={!lectura.trim()||importando}>{importando?"Importando…":"Importar lectura"}</button>{importando&&<span className="gc-importing" role="status">Procesando lectura y comparando con el histórico de OEX…</span>}</div>
  </section>
  {ultimoResultado&&<section className="gc-panel"><div className="gc-panel-head"><div><h3>Resultado de la última importación</h3><p>{ultimoResultado.total} leídos · {ultimoResultado.nuevos} nuevos · {ultimoResultado.actualizados||0} avanzaron · {ultimoResultado.sinCambios||0} sin cambios · {ultimoResultado.finalizados||0} finalizados · {ultimoResultado.errores} errores</p></div></div><div className="gc-history">{(ultimoResultado.detalle||[]).filter(d=>String(d.accion||"").includes("_a_")).length>0&&<div className="gc-state-changes"><b>Cambios de estado realizados</b>{(ultimoResultado.detalle||[]).filter(d=>String(d.accion||"").includes("_a_")).map((d,i)=><div className="gc-detail" key={`cambio-${i}`}><code>{d.tracking||"—"}</code><span>{d.anterior||"—"} → {d.final||"—"} · Almacén {d.almacenId||"—"}</span></div>)}</div>}{(ultimoResultado.detalle||[]).map((d,i)=><div className="gc-detail" key={i}><code>{d.tracking||"—"}</code><span>Almacén {d.almacenId||"—"} · Global: {d.statusGlobal||"Sin estado"} · OEX: {d.anterior?d.anterior+" → ":""}{d.final||"—"}</span></div>)}</div></section>}
  <section className="gc-panel"><div className="gc-panel-head"><div><h3>Paquetes sin asignar</h3><p>Recibidos en Miami que no estaban registrados en OEX.</p></div></div>
   {cargando?<p>Cargando recepciones…</p>:pendientes.length===0?<div className="gc-empty"><CheckCircle2 size={26}/><b>Todo está asignado</b><span>No hay paquetes pendientes de cliente.</span></div>:<div className="gc-list">{pendientes.map(r=>{const f=form[r.id]||{};const ref=r.detalle?.referencia_global||r.nombre_global||"";const instr=String(r.detalle?.instrucciones_global||"").trim().toUpperCase();const tipoDetectado=instr==="AIR"?"Aéreo":/(SEA|OCEAN|MARIT)/.test(instr)?"Marítimo":"";return <article className="gc-card" key={r.id}><div className="gc-card-main"><div><small>TRACKING</small><b>{r.tracking}</b></div><div><small>ID ALMACÉN</small><b>{r.almacen_id}</b></div><div><small>NOMBRE / REFERENCIA</small><b>{ref||"Sin nombre"}</b>{instr&&<span>Instrucciones: {instr}</span>}{tipoDetectado&&<span>Tipo detectado: {tipoDetectado}</span>}</div><div><small>RECIBIDO MIAMI</small><b>{r.fecha_miami?new Date(r.fecha_miami).toLocaleDateString():"—"}</b></div></div><div className="gc-assign"><select value={f.clienteId||""} onChange={e=>setForm(x=>({...x,[r.id]:{...f,clienteId:e.target.value}}))}><option value="">Asignar cliente…</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><select value={f.destino||""} onChange={e=>setForm(x=>({...x,[r.id]:{...f,destino:e.target.value}}))}><option value="">Destino…</option><option>Managua</option><option>Ometepe</option></select><select value={f.tipoEnvio||tipoDetectado||""} onChange={e=>setForm(x=>({...x,[r.id]:{...f,tipoEnvio:e.target.value}}))}><option value="">Tipo…</option><option>Aéreo</option><option>Marítimo</option></select><button className="btn btn-primary" disabled={asignando===r.id} onClick={()=>asignar(r)}>{asignando===r.id?"Asignando…":"Asignar y activar"}</button></div></article>})}</div>}
  </section>
  <section className="gc-panel"><div className="gc-panel-head"><div><h3>Historial de sincronización</h3><p>Resumen de lo que OEX hizo en Global Connect.</p></div></div><div className="gc-history">{runs.map(r=><details key={r.id}><summary><span>{new Date(r.creado_en).toLocaleString()}</span><b>{r.total_detectados} detectados · {r.prealertas_confirmadas} confirmados · {r.sin_asignar_nuevos} nuevos</b></summary><div className="gc-detail">{(r.detalle||[]).map((d,i)=><div key={i}><code>{d.tracking||d.almacenId||"—"}</code><span>{String(d.accion||"").replaceAll("_"," ")}</span></div>)}</div></details>)}</div>
  </section>
 </div>
}
