// src/pages/Dashboard.jsx
import { useMemo } from "react";
import { Package, TrendingUp, Wallet, Clock, Users, AlertCircle, Warehouse, DollarSign, Weight, ReceiptText } from "lucide-react";
import { numero } from "../utils/numero";
import Metric from "../components/Metric";
import SeguimientoClientes from "../components/SeguimientoClientes";
import { esPendienteDeConfirmar, esListoParaRetiroProveedor } from "../utils/estadosEnvio";
import { calcularDeadlineTracking } from "../utils/deadlinesEntrega";
import { useFeriadosNicaragua } from "../hooks/useFeriadosNicaragua";
import "../styles/Dashboard.css";

const FRASES=["Cada entrega cuenta.","Lo que se mide, se puede mejorar.","Cada paquete entregado es un cliente que confió en OEX.","Hoy es un buen día para mover OEX hacia adelante.","Un cliente bien atendido siempre recuerda el servicio.","Orden, seguimiento y servicio hacen crecer cada envío.","Cada libra mueve una historia y una oportunidad.","Hagamos que cada entrega llegue mejor que la anterior."];
const fechaDe=x=>{const v=x?.fechaISO||x?.fecha||x?.createdAt||x?.created_at;if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d;};

export default function Dashboard({pedidos,envios,gastos,prealertas=[],empresa,cuentasDinero=[],auth,mostrarToast,cargarDatos,setVista,irAPrealertas}){
 const feriados=useFeriadosNicaragua();
 const ahora=new Date(),mes=ahora.getMonth(),anio=ahora.getFullYear();const esMesActual=x=>{const d=fechaDe(x);return d&&d.getMonth()===mes&&d.getFullYear()===anio;};
 const nombre=(auth?.usuarioActual?.nombre||auth?.session?.user?.user_metadata?.nombre||auth?.session?.user?.email||"equipo OEX").split(" ")[0];const h=ahora.getHours(),saludo=h>=5&&h<12?"Buenos días":h>=12&&h<18?"Buenas tardes":"Buenas noches";const frase=FRASES[Math.floor((ahora-new Date(anio,0,1))/86400000)%FRASES.length];
 const enviosMes=envios.filter(esMesActual),gastosMes=gastos.filter(esMesActual);const factMes=enviosMes.reduce((a,e)=>a+numero(e.total),0),factHist=envios.reduce((a,e)=>a+numero(e.total),0);const ganMes=enviosMes.reduce((a,e)=>a+numero(e.gananciaReal),0),ganHist=envios.reduce((a,e)=>a+numero(e.gananciaReal),0);const gasMes=gastosMes.reduce((a,g)=>a+numero(g.monto),0),gasHist=gastos.reduce((a,g)=>a+numero(g.monto),0);const porCobrar=envios.reduce((a,e)=>a+numero(e.saldo),0);
 const recibosActivos=envios.filter(e=>e.estado!=="Entregado"),prePend=prealertas.filter(esPendienteDeConfirmar),activos=prealertas.filter(t=>!esPendienteDeConfirmar(t));const bodega=useMemo(()=>prealertas.filter(t=>esListoParaRetiroProveedor(t.estado)),[prealertas]);const librasMes=enviosMes.reduce((a,e)=>a+numero(e.totalLibras),0),librasHist=envios.reduce((a,e)=>a+numero(e.totalLibras),0);const clientesMes=new Set(enviosMes.map(e=>e.clienteId||e.clienteCodigo||e.cliente).filter(Boolean)).size;
 const ranking=useMemo(()=>{const m=new Map();envios.forEach(e=>{const k=e.clienteId||e.clienteCodigo||e.cliente;if(!k)return;const x=m.get(k)||{nombre:e.cliente||e.clienteCodigo||"Cliente",libras:0,monto:0};x.libras+=numero(e.totalLibras);x.monto+=numero(e.total);m.set(k,x);});const v=[...m.values()];return{libras:[...v].sort((a,b)=>b.libras-a.libras)[0]||null,monto:[...v].sort((a,b)=>b.monto-a.monto)[0]||null};},[envios]);const saldoCount=envios.filter(e=>numero(e.saldo)>0).length;
 const deadlines=useMemo(()=>activos.map(t=>({tracking:t,deadline:calcularDeadlineTracking(t,feriados,ahora)})).filter(x=>x.deadline),[activos,feriados]);
 const vencidos=deadlines.filter(x=>x.deadline.estadoDeadline==="vencido");
 const proximos=deadlines.filter(x=>x.deadline.estadoDeadline==="proximo");
 const alertas=[
  vencidos.length>0&&{texto:`🔴 ${vencidos.length} envío${vencidos.length===1?"":"s"} fuera del plazo prometido`,accion:()=>setVista("paqueteria")},
  proximos.length>0&&{texto:`⏰ ${proximos.length} envío${proximos.length===1?"":"s"} a 2 días hábiles o menos del deadline`,accion:()=>setVista("paqueteria")},
  prePend.length>0&&{texto:`${prePend.length} prealerta${prePend.length===1?"":"s"} pendiente${prePend.length===1?"":"s"} de revisión`,accion:irAPrealertas},
  bodega.length>0&&{texto:`${bodega.length} paquete${bodega.length===1?"":"s"} listo${bodega.length===1?"":"s"} para retirar en Bodega OEX`,accion:()=>setVista("paqueteria")},
  saldoCount>0&&{texto:`${saldoCount} recibo${saldoCount===1?"":"s"} con saldo pendiente · $${porCobrar.toFixed(2)}`,accion:()=>setVista("paqueteria")}
 ].filter(Boolean);
 const ultimos=[...pedidos.slice(0,3).map(p=>({...p,tipo:"SHEIN"})),...envios.slice(0,3).map(e=>({...e,tipo:"Paquetería"}))].sort((a,b)=>(fechaDe(b)?.getTime()||0)-(fechaDe(a)?.getTime()||0)).slice(0,5);
 return <div className="page dashboard-page"><section className="dashboard-greeting"><div><h1>{saludo}, {nombre} 👋</h1><p>{frase}</p></div><span>Resumen de hoy</span></section>
 {alertas.length>0&&<section className="dashboard-alert-zone" aria-label="Alertas pendientes"><div className="dashboard-alert-heading"><span className="dashboard-alert-light" aria-hidden="true"/><b>Requiere atención</b></div><div className="dashboard-alerts dashboard-alerts-top">{alertas.map((a,i)=><button key={i} type="button" onClick={a.accion}><span className="dashboard-alert-dot" aria-hidden="true"/><AlertCircle size={15}/><span>{a.texto}</span></button>)}</div></section>}
 <section className="dashboard-section"><div className="dashboard-section-title"><h2>Salud del negocio</h2><small>Este mes</small></div><div className="dashboard-metrics"><Metric label={<><DollarSign size={16}/> Facturación</>} value={`$${factMes.toFixed(2)}`} onClick={()=>setVista("paqueteria")}/><Metric label={<><TrendingUp size={16}/> Ganancia real</>} value={`$${ganMes.toFixed(2)}`}/><Metric label={<><Wallet size={16}/> Gastos</>} value={`$${gasMes.toFixed(2)}`} onClick={()=>setVista("finanzas")}/><Metric label={<><ReceiptText size={16}/> Por cobrar</>} value={`$${porCobrar.toFixed(2)}`} onClick={()=>setVista("paqueteria")}/></div><div className="dashboard-history">Histórico · Facturado <b>${factHist.toFixed(2)}</b><span>Ganancia <b>${ganHist.toFixed(2)}</b></span><span>Gastos <b>${gasHist.toFixed(2)}</b></span></div></section>
 <section className="dashboard-section"><div className="dashboard-section-title"><h2>Operación actual</h2><small>En tiempo real</small></div><div className="dashboard-metrics"><Metric label={<><Package size={16}/> Envíos activos</>} value={activos.length} onClick={()=>setVista("paqueteria")}/><Metric label={<><AlertCircle size={16}/> Prealertas</>} value={prePend.length} onClick={irAPrealertas}/><Metric label={<><Clock size={16}/> Recibos activos</>} value={recibosActivos.length} onClick={()=>setVista("paqueteria")}/><Metric label={<><Warehouse size={16}/> Bodega OEX</>} value={bodega.length} onClick={()=>setVista("paqueteria")}/></div></section>
 <section className="dashboard-section"><div className="dashboard-section-title"><h2>Clientes y volumen</h2><small>Rendimiento</small></div><div className="dashboard-metrics"><div className="metric"><b><Weight size={15}/> Libras del mes</b><span className="metric-value">{librasMes.toFixed(1)} lb</span><small>{librasHist.toFixed(1)} lb históricas</small></div><div className="metric"><b><Users size={15}/> Clientes del mes</b><span className="metric-value">{clientesMes}</span></div><div className="metric"><b>Top por libras</b><span className="metric-value dashboard-top-name">{ranking.libras?.nombre||"—"}</span><small>{ranking.libras?`${ranking.libras.libras.toFixed(1)} lb`:"Sin datos"}</small></div><div className="metric"><b>Top por facturación</b><span className="metric-value dashboard-top-name">{ranking.monto?.nombre||"—"}</span><small>{ranking.monto?`$${ranking.monto.monto.toFixed(2)}`:"Sin datos"}</small></div></div></section>
 <section className="dashboard-section dashboard-activity"><div className="dashboard-section-title"><h2>Actividad reciente</h2></div><div className="list">{ultimos.map((u,i)=><div className="row-card" key={`${u.id||u.numero||i}-${i}`}><div><b>{u.numero||u.tracking||"Registro"}</b><p>{u.cliente||"—"} · {u.tipo}</p></div><span className="badge badge-neutral">{u.estado||"Registrado"}</span></div>)}{ultimos.length===0&&<p>Sin actividad reciente.</p>}</div></section><SeguimientoClientes envios={envios} empresa={empresa} cuentasDinero={cuentasDinero} auth={auth} mostrarToast={mostrarToast} cargarDatos={cargarDatos}/></div>;
}
