import { useEffect, useMemo, useState } from "react";
import { FileSpreadsheet, FileText, BookOpen, BarChart3, Scale, Package, ReceiptText, Truck, Landmark, Library, Camera } from "lucide-react";
import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";
import { supabase } from "../../supabase";
import { numero } from "../../utils/numero";
import EstadoResultadosReporte from "./EstadoResultadosReporte";
import FinanzasLibroDiario from "./FinanzasLibroDiario";

const hoyISO = () => new Date().toISOString().slice(0, 10);
const nombreArchivo = (base, ext) => `${base}-${hoyISO()}.${ext}`;
const descargarExcel = (nombre, filas, hoja = "Reporte") => { const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(filas), hoja); XLSX.writeFile(wb, nombreArchivo(nombre, "xlsx")); };
const descargarPDF = (titulo, filas, nombre) => { const doc = new jsPDF(); doc.setFontSize(16); doc.text(titulo, 14, 18); doc.setFontSize(9); let y = 28; filas.forEach(fila => { const linea = Object.entries(fila).map(([k,v])=>`${k}: ${v}`).join("  |  "); const lineas=doc.splitTextToSize(linea,180); if(y+lineas.length*5>285){doc.addPage();y=18;} doc.text(lineas,14,y); y+=lineas.length*5+2; }); doc.save(nombreArchivo(nombre,"pdf")); };
const normalizarTipo = (tipo="") => { const t=String(tipo).toLowerCase(); if(t.includes("activo")) return "activo"; if(t.includes("pasivo")) return "pasivo"; if(t.includes("patrimonio")||t.includes("capital")) return "patrimonio"; if(t.includes("ingreso")) return "ingreso"; if(t.includes("costo")) return "costo"; if(t.includes("gasto")) return "gasto"; return null; };

function BalanceGeneral({ cuentasContables=[], mostrarToast }) {
 const [movimientos,setMovimientos]=useState([]),[cargando,setCargando]=useState(true);
 useEffect(()=>{let activo=true;setCargando(true);supabase.from("movimientos_contables").select("debe, haber, cuentas_contables(id,codigo,nombre,tipo)").then(({data,error})=>{if(!activo)return;if(error)throw error;setMovimientos(data||[]);}).catch(()=>activo&&setMovimientos([])).finally(()=>activo&&setCargando(false));return()=>{activo=false;};},[]);
 const cuentas=useMemo(()=>{const mapa=new Map();movimientos.forEach(m=>{const c=m.cuentas_contables;if(!c)return;const tipo=normalizarTipo(c.tipo)||normalizarTipo(cuentasContables.find(x=>x.id===c.id)?.tipo);if(!tipo)return;if(!mapa.has(c.id))mapa.set(c.id,{codigo:c.codigo,nombre:c.nombre,tipo,debe:0,haber:0});const x=mapa.get(c.id);x.debe+=numero(m.debe);x.haber+=numero(m.haber);});return[...mapa.values()].map(x=>({...x,saldo:["activo","costo","gasto"].includes(x.tipo)?x.debe-x.haber:x.haber-x.debe})).filter(x=>Math.abs(x.saldo)>.005).sort((a,b)=>String(a.codigo).localeCompare(String(b.codigo)));},[movimientos,cuentasContables]);
 const porTipo=tipo=>cuentas.filter(x=>x.tipo===tipo), total=tipo=>porTipo(tipo).reduce((a,x)=>a+x.saldo,0);
 const utilidadAcumulada=total("ingreso")-total("costo")-total("gasto");
 const activos=total("activo"),pasivos=total("pasivo"),patrimonioBase=total("patrimonio"),patrimonio=patrimonioBase+utilidadAcumulada,diferencia=activos-pasivos-patrimonio;
 const filasBalance=[...porTipo("activo"),...porTipo("pasivo"),...porTipo("patrimonio"),{tipo:"patrimonio",codigo:"—",nombre:"Resultado acumulado",saldo:utilidadAcumulada}];
 const exportRows=filasBalance.map(x=>({Tipo:x.tipo,Código:x.codigo,Cuenta:x.nombre,Saldo:Number(x.saldo.toFixed(2))}));
 if(cargando)return <div className="card"><p>Cargando balance general…</p></div>;
 const renderTipo=(tipo,extra=[])=>{const filas=[...porTipo(tipo),...extra];return <div className="card"><h3 style={{textTransform:"capitalize"}}>{tipo}</h3><div className="list mt-16">{filas.map((x,i)=><div className="row-card" key={`${x.codigo}-${i}`}><div><b>{x.codigo} · {x.nombre}</b></div><b>${x.saldo.toFixed(2)}</b></div>)}{filas.length===0&&<p>Sin saldos en esta sección.</p>}</div></div>;};
 return <div><div className="segment"><button className="btn" onClick={()=>{descargarExcel("balance-general",exportRows,"Balance general");mostrarToast?.("Balance general descargado en Excel.");}}><FileSpreadsheet size={14}/>Excel</button><button className="btn" onClick={()=>{descargarPDF("Balance general",exportRows,"balance-general");mostrarToast?.("Balance general descargado en PDF.");}}><FileText size={14}/>PDF</button></div><div className="grid-4"><div className="metric"><b>Activos</b><span className="metric-value">${activos.toFixed(2)}</span></div><div className="metric"><b>Pasivos</b><span className="metric-value">${pasivos.toFixed(2)}</span></div><div className="metric"><b>Patrimonio + resultado</b><span className="metric-value">${patrimonio.toFixed(2)}</span></div><div className="metric"><b>Diferencia</b><span className="metric-value" style={{color:Math.abs(diferencia)<.01?"var(--success)":"var(--danger)"}}>${diferencia.toFixed(2)}</span></div></div>{renderTipo("activo")}{renderTipo("pasivo")}{renderTipo("patrimonio",[{codigo:"—",nombre:"Resultado acumulado",saldo:utilidadAcumulada}])}</div>;
}

const GLOSARIO=[["Ventas","Valor total facturado a clientes.","Suma de recibos emitidos."],["Costo económico","Costo congelado asociado a los trackings de cada recibo.","Peso × tarifa de proveedor guardada para la operación."],["Margen bruto estimado","Lo que queda de las ventas después del costo económico de los envíos.","Ventas − costo económico."],["Gastos operativos","Salidas por transporte, administración u otros gastos que no son costo directo del proveedor.","Suma de gastos registrados."],["Utilidad neta estimada","Resultado económico esperado de la operación.","Margen bruto estimado + otros ingresos − gastos operativos."],["Utilidad neta cobrada","Parte del margen de ventas ya cobradas, después de gastos.","Margen de operaciones cobradas y con proveedor pagado − gastos operativos."],["Utilidad estimada por cobrar","Margen asociado a ventas cuyo cliente todavía tiene saldo.","Suma del margen de recibos con saldo pendiente."],["Ventas por cobrar","Dinero que los clientes todavía deben.","Suma de saldos pendientes de recibos."],["Liquidez","Dinero físicamente registrado en cajas y bancos.","Saldos actuales por cuenta; USD y NIO se presentan separados."],["Capital financiado a clientes","Costo que OEX ya pagó al proveedor pero cuyo cliente todavía debe.","Costo de recibos pendientes con proveedor pagado."],["Costo pendiente de facturar","Costo congelado de paquetes que todavía no aparece en una factura formal del proveedor.","Costo económico pendiente de factura; no es CxP formal."],["Cuentas por pagar","Deuda formal registrada con proveedores.","Saldo pendiente de facturas de proveedor."],["Resultado contable","Resultado basado en los costos y gastos ya reconocidos en el libro diario.","Ingresos contables − costos contabilizados − gastos contabilizados."]];


function CentroReportes({envios,prealertas,facturasProveedor,cuentasDinero,gastos,ingresos,empresa,auth,mostrarToast}){
 const corte=new Date();const corteTxt=corte.toLocaleString("es-NI");const ventas=envios.reduce((a,e)=>a+numero(e.total),0),costos=envios.reduce((a,e)=>a+numero(e.costoInternoTotal),0),margen=envios.reduce((a,e)=>a+numero(e.gananciaReal),0),gasto=gastos.reduce((a,e)=>a+numero(e.monto),0),otros=ingresos.reduce((a,e)=>a+numero(e.monto),0),utilidad=margen+otros-gasto,porCobrar=envios.reduce((a,e)=>a+numero(e.saldo),0),utilidadPorCobrar=envios.filter(e=>numero(e.saldo)>0).reduce((a,e)=>a+numero(e.gananciaReal),0),cxp=facturasProveedor.reduce((a,f)=>a+numero(f.saldo),0);
 const resumen=[{Concepto:"Ventas acumuladas",Valor:ventas},{Concepto:"Costo económico",Valor:costos},{Concepto:"Margen bruto estimado",Valor:margen},{Concepto:"Gastos operativos",Valor:gasto},{Concepto:"Otros ingresos",Valor:otros},{Concepto:"Utilidad neta estimada",Valor:utilidad},{Concepto:"Ventas por cobrar",Valor:porCobrar},{Concepto:"Utilidad estimada por cobrar",Valor:utilidadPorCobrar},{Concepto:"Cuentas por pagar",Valor:cxp}];
 const trackings=prealertas.map(t=>({Tracking:t.tracking||t.codigo,Estado:t.estado,Tipo:t.tipoEnvio,Destino:t.destino,Peso:numero(t.peso),Proveedor:t.proveedorNombre||t.proveedor||"",Fecha:t.fecha||t.fechaISO||""}));
 const recibos=envios.map(e=>({Recibo:e.numero||e.numeroEnvios,Cliente:e.cliente,Fecha:e.fecha||e.fechaISO,Estado:e.estado,Total:numero(e.total),Abono:numero(e.abono),Saldo:numero(e.saldo),"Costo económico":numero(e.costoInternoTotal),"Margen estimado":numero(e.gananciaReal),Trackings:(e.trackings||[]).map(t=>t.tracking||t.codigo).filter(Boolean).join(", ")}));
 const proveedores=facturasProveedor.map(f=>({Factura:f.numeroFactura||f.numero_factura,Proveedor:f.proveedorNombre||f.proveedor||"",Fecha:f.fecha||f.fechaISO,"Monto estimado":numero(f.montoEstimado),"Monto real":numero(f.montoReal),Abonado:numero(f.abonado),Saldo:numero(f.saldo),Estado:f.estado}));
 const bancos=cuentasDinero.filter(x=>x.activa!==false).map(x=>({Cuenta:x.nombre,Moneda:x.moneda,"Saldo actual":numero(x.saldoActual)}));
 const meta=[{Campo:"Empresa",Valor:empresa?.nombre||"OEX"},{Campo:"Fecha de corte",Valor:corteTxt},{Campo:"Generado por",Valor:auth?.usuarioActual?.nombre||auth?.session?.user?.email||"Usuario OEX"}];
 const crear=(nombre,hojas)=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(meta),"Información");hojas.forEach(([n,rows])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),n));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["Concepto","Definición","Cálculo"],...GLOSARIO]),"Glosario");XLSX.writeFile(wb,nombreArchivo(nombre,"xlsx"));mostrarToast?.("Reporte Excel generado.");};
 const tarjetas=[["Trackings",Package,()=>crear("oex-trackings",[["Trackings",trackings]])],["Recibos",ReceiptText,()=>crear("oex-recibos",[["Recibos",recibos]])],["Proveedores",Truck,()=>crear("oex-proveedores",[["Proveedores",proveedores]])],["Bancos y caja",Landmark,()=>crear("oex-bancos",[["Cuentas",bancos]])],["Estado a la fecha",Camera,()=>crear("oex-estado-a-la-fecha",[["Resumen",resumen],["Cuentas",bancos],["Recibos",recibos],["Proveedores",proveedores]])]];
 return <div><div className="card"><h3>Estado financiero a la fecha</h3><p>Corte: <b>{corteTxt}</b>. Los saldos bancarios conservan su moneda original.</p><div className="grid-4 mt-16"><div className="metric"><b>Utilidad neta estimada</b><span className="metric-value">${utilidad.toFixed(2)}</span></div><div className="metric"><b>Ventas por cobrar</b><span className="metric-value">${porCobrar.toFixed(2)}</span></div><div className="metric"><b>Utilidad por cobrar</b><span className="metric-value">${utilidadPorCobrar.toFixed(2)}</span></div><div className="metric"><b>CxP formal</b><span className="metric-value">${cxp.toFixed(2)}</span></div></div></div><div className="grid-4 mt-16">{tarjetas.map(([n,I,fn])=><button className="card" key={n} onClick={fn} style={{textAlign:"left",cursor:"pointer"}}><I size={20}/><h3>{n}</h3><p>Generar Excel estructurado con fecha de corte y glosario.</p></button>)}</div></div>;
}

export default function FinanzasReportes({ cuentasContables=[], envios=[], prealertas=[], facturasProveedor=[], cuentasDinero=[], gastos=[], ingresos=[], empresa, auth, mostrarToast }) {
 const [reporte,setReporte]=useState(()=>localStorage.getItem("oex_finanzas_reporte")||"centro");
 useEffect(()=>{localStorage.setItem("oex_finanzas_reporte",reporte);},[reporte]);
 return <div><div className="card"><div className="page-title" style={{margin:0}}><div><h3>Centro de reportes</h3><p>Fotografías financieras y reportes operativos con fecha de corte.</p></div></div><div className="segment mt-16"><button className={`segment-btn ${reporte==="centro"?"active":""}`} onClick={()=>setReporte("centro")}><FileSpreadsheet size={14}/> Centro</button><button className={`segment-btn ${reporte==="resultados"?"active":""}`} onClick={()=>setReporte("resultados")}><BarChart3 size={14}/> Resultados</button><button className={`segment-btn ${reporte==="libro"?"active":""}`} onClick={()=>setReporte("libro")}><BookOpen size={14}/> Libro diario</button><button className={`segment-btn ${reporte==="balance"?"active":""}`} onClick={()=>setReporte("balance")}><Scale size={14}/> Balance</button><button className={`segment-btn ${reporte==="glosario"?"active":""}`} onClick={()=>setReporte("glosario")}><Library size={14}/> Glosario</button></div></div>
 {reporte==="centro"&&<CentroReportes envios={envios} prealertas={prealertas} facturasProveedor={facturasProveedor} cuentasDinero={cuentasDinero} gastos={gastos} ingresos={ingresos} empresa={empresa} auth={auth} mostrarToast={mostrarToast}/>}
 {reporte==="resultados"&&<EstadoResultadosReporte/>}{reporte==="libro"&&<FinanzasLibroDiario/>}{reporte==="balance"&&<BalanceGeneral cuentasContables={cuentasContables} mostrarToast={mostrarToast}/>}
 {reporte==="glosario"&&<div className="card"><h3>Glosario financiero OEX</h3><p>Definiciones oficiales usadas en dashboards y reportes.</p><div className="list mt-16">{GLOSARIO.map(([n,d,f])=><div className="row-card" key={n}><div><b>{n}</b><p>{d}</p><small><b>Cálculo:</b> {f}</small></div></div>)}</div></div>}</div>;
}